services:
  - type: web
    name: tradingview-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/api_tradingview.py"
    envVars:
      - key: PORT
        value: 5000
